title: 桜の空と迷い猫
description: >
  その女の子は、体に似つかわしくない大きな荷物を背負っていた。そればかりか、その荷物から驚くほどの勢いでピンク色の煙を吐き出していた。――小さな魔女とぼくの、ある日の記憶。
index: auto

author: 8amjp
image: site-icon.png
type: novel
card: summary
google_analytics: UA-41627578-3
twitter:
  username: 8amjp

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-seo-tag